name: Dispatcher
on:
  push:
    branches: [main]

jobs:
  dispatch:
    name: Dispatch
    # env:
    #   PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     repo: ['louise-x/learn-git']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "some_event_01", "client_payload": { "foo": "${{ github.sha }}" }}' https://api.github.com/repos/louise-x/learn-git/dispatches